Over today's practice you'll learn:
* to use JuPyter notebooks to quickly prototype code and show results
* the numerical Python library

This lab is divided in two parts. In each of them, you will have to fill in the gaps following the instructions given.
The prompts for you to write code will look like this:

In [ ]:
#<------------INSERT CODE HERE------------>

This might involve more than one line of code from you!

Do **not** delete code from the notebook.

Let's start!

## Part 1

In the first part of the lab we're going to check your Python skills and, in particular, we will ask you to create some functions to operate on vectors and matrices.



### Operations with vectors

In [25]:
# Let's create a vector. We can do this as a Python built-in type: the list
vector1 = [1, 2, 4, 78, 93] # we declare the vector as a list of elements

print(vector1)
print("The vector has %d elements" % len(vector1))

[1, 2, 4, 78, 93]
The vector has 5 elements


In [16]:
# Let's add a number to every element of the vector.
## Exercise: create a function that, given a vector and a number,
## returns the addition of that number to each element of the vector
def vector_plus_num(vector, number):
    #<------------INSERT CODE HERE------------>
    for i in range(0, len(vector1)):
        vector[i] += number # Add the number to each element in turn
    return vector

In [17]:
# Let's test your function:
print(vector_plus_num(vector1, 5))
print(vector_plus_num(vector1, -33))

[6, 7, 9, 83, 98]
[-27, -26, -24, 50, 65]


What if we now wanted to mutiply a number and a vector? **Do not do it**, just think about what you'd need!

And what if we want to calculate the mean value of your vector?

In [18]:
## Exercise: create a function that, given a vector,
## returns the mean value of its elements.
def vector_mean(vector):
    #<------------INSERT CODE HERE------------>
    l = len(vector)
    mu = 0
    for i in range (0, l):
        mu = mu + vector[i] # Sum each element in turn
        
    mu = mu / l # Finally, divide by the number of elements (quicker than dividing after each element)
    return mu

In [25]:
# Now test your function:
print(f"The average is: {vector_mean(vector1)}.")
#<------------INSERT CODE HERE------------>

The average is: 35.6.


We will now work on operations between pairs of vectors.

In [26]:
# Now let's create a new vector, called vector2, of the same length as vector1.
# We will then look at operations with multiple vectors, 
# such as adding and subtracting them, and vector multiplications.
vector2 = [-1 for i in range(0, len(vector1))]#<------------INSERT CODE HERE------------>
#print(vector2) # Debug
assert len(vector1) == len(vector2), "The vectors are not of the same length"

In [53]:
# Create a function that returns new vector of the same length as vector1 and vector2, 
# for which each element is the sum of the corresponding elements from vector1 and vector2.

# Feel free to create a function to do this!

def add_two_vectors(vec1, vec2):
    #<------------INSERT CODE HERE------------>
    assert len(vec1) == len(vec2), "The vectors are not of the same length"
    # Assuming both vectors are same length (assert catch-all from above), use length of first as reference
    sumVec = []
    for i in range(0, len(vec1)):
        sumVec.append(vec1[i] + vec2[i])
    return sumVec

In [55]:
# Let's test your function:
print(add_two_vectors(vector1, vector2))
print(add_two_vectors(vector1, [1, 2, 3]))
# If the second print resulted in an error, don't worry about it for now!

[0, 1, 3, 77, 92]


AssertionError: The vectors are not of the same length

How about the multiplication of vectors?
There are two types of vector multiplications:
* The dot product (or scalar product) takes two vectors and returns a scalar.
* The cross product (or vector product) takes two vectors and returns another vector.

Now let's create a function that returns the scalar product of two vectors.

This can be done by multiplying pairs of elements and adding the result:

A = [A1, A2, A3, ..., An]

B = [B1, B2, B3, ..., Bn]

A · B = A1·B1 + A2·B2 + ... An·Bn

In [56]:
def scalar_product(v1, v2):
    #<------------INSERT CODE HERE------------>
    # Catch if unequal vectors entered
    assert len(v1) == len(v2), "The vectors are not of the same length"
    # If ok, perform the calc
    scalarProduct = 0
    l = len(v1)
    for i in range(0, l):
        scalarProduct+= v1[i]*v2[i]
    return scalarProduct

In [57]:
# Test your function
print(f"The scalar product is: {scalar_product(vector1, vector2)}.")
#<------------INSERT CODE HERE------------>

The scalar product is: -178.


### Operations with matrices

Again, there are multiple things we can do with matrices. For example, adding/subtracting/multiplying a number to each element of a matrix and matrix multiplication.

We're going to attempt the last one only.

In [19]:
# Create a function that receives two matrices as input and returns the matrix multiplication of the two
# If you don't know how to multiply two matrices, check:
# https://en.wikipedia.org/wiki/Matrix_multiplication#Definition

def matrix_multiplication(matrix1, matrix2):
    #Using matrix A and matrix D, 3 x 2, 2 x 3
    multipl_result = []
    #<------------INSERT CODE HERE------------>
    # Test if matrix1[x] == matrix2[y]
    assert len(matrix1[0]) == len(matrix2), "Matrix dimensions don't match!"
    # Multiply each row item of matrix A by column item of matrix B
    # Now assume that m1 rows = m2 cols and vice versa
    rows = len(matrix1) # 2
    cols = len(matrix2) # 3
    # Process each row of matrix 1..
    for i in range(0, rows):
        # ..by each column in matrix 2
        for j in range(0, rows):
            summ = 0
            # Third inner loop as we need to sum each column of matrix B for each row of matrix A
            # This inner loop just sums each row element * col element
            for k in range(0, cols):
                summ = summ + matrix1[i][k]*matrix2[k][j]
                #print(f"Multiplying {matrix1[i][k]} by {matrix2[k][j]}")
            #print("Appending")
            multipl_result.append(summ)
    return multipl_result
# matrix1 [1,2,3]
#         [1,2,3]

# matrix2 [10,11]
#         [10,11]
#         [10,11]
print(matrix_multiplication(matrixA, matrixD))

[60, 66, 60, 66]


In [2]:
# And let's test your function:
# NOTE: some of the tests below will give errors. Don't worry about them!
matrixA = [[1, 2, 3], [1, 2, 3]]
matrixB = [[5, 6, 7], [5, 6, 7], [5, 6, 7]]
matrixC = [[8, 9], [8, 9], [8, 9], [8, 9]]
matrixD = [[10, 11], [10, 11], [10, 11]]

In [ ]:
print(matrix_multiplication(matrixA, matrixB))

In [ ]:
print(matrix_multiplication(matrixA, matrixC))

In [68]:
print(matrix_multiplication(matrixA, matrixD))

[[30], [33]]


Hopefully this has convinced you that operating with vectors and matrices like this is not the best way.
Now we will turn to the second part of this lab, in which you will be introduced to the numerical Python library, *numpy*.

## Part 2: Numpy


Numpy has a built-in type called the *ndarray*. 

In [27]:
import numpy as np # Importing convention for Numpy

#### Creating and manipulating arrays

In [28]:
# Create arrays with a specified data type

arr = np.array([1, 2, 3], dtype=np.float32)
print(arr)
print(arr.dtype)

arr = np.array([1+2j, 3-4j], dtype=np.complex64)  # an array of complex numbers
print(arr)
print(arr.dtype)

arr = np.array([0, 1, 1], dtype=np.bool)  # an array of True/False values
print(arr)
print(arr.dtype)

# We can also create arrays from the vectors and matrices we had before.
arr = np.array(matrixA)
print(arr)
print(arr.dtype)
print(arr.shape)

arr = np.array(vector2)
print(arr)
print(arr.dtype)
print(arr.shape)


[1. 2. 3.]
float32
[1.+2.j 3.-4.j]
complex64
[False  True  True]
bool
[[1 2 3]
 [1 2 3]]
int32
(2, 3)
[-1 -1 -1 -1 -1]
int32
(5,)


In [29]:
arr_range2 = np.arange(10)
print(arr_range2)

# Retrieving information on the array
print("shape:", arr_range2.shape)
print("dtype:", arr_range2.dtype)
print("dim:", arr_range2.ndim)
print("itemsize:", arr_range2.itemsize)

[0 1 2 3 4 5 6 7 8 9]
shape: (10,)
dtype: int32
dim: 1
itemsize: 4


In [30]:
# We can use the np.arange function to create a range of values:
arr = np.arange(0, 100, 5) #np.arange(start, stop, pace)
print(arr)
# Note: is the last value (100) included?

# Similarly, we can use np.linspace:
# np.linspace(start, stop, num_of_elements, endpoint=True) 
arr = np.linspace(0, 10, 20)
print(arr)
# Note: is the last value (10) included now?

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [31]:
arr_2d = np.array([(1.5, 2, 3), (4, 5, 6)]) # creating an array from a list of tuples
print(arr_2d)
print(arr_2d.shape)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
(2, 3)


In [32]:
# Slicing (i.e., accessing specific elements of the array)

print("arr_2d[0,0] :", arr_2d[0, 0])
print("arr_2d[0,:] : ", arr_2d[0, :])
print("arr_2d[:,0] :", arr_2d[:, 0])

print(arr_2d[arr_2d > 2])

arr_2d[0,0] : 1.5
arr_2d[0,:] :  [1.5 2.  3. ]
arr_2d[:,0] : [1.5 4. ]
[3. 4. 5. 6.]


In [33]:
# Other types of arrays

zeros = np.zeros((10, 10))
print(zeros)
# print the shape of zeros
#<------------INSERT CODE HERE------------>

ones = np.ones((4, 4))
print(ones)
# print the shape of ones
#<------------INSERT CODE HERE------------>

print(ones.reshape(2, 8))
# print the shape of ones
#<------------INSERT CODE HERE------------>

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# We can also use numpy to generate random values.
randn = np.random.randn(1, 1000)
# print the shape of randn
#<------------INSERT CODE HERE------------>

# print the first 10 elements of randn. What happens if you re-run this code?
#<------------INSERT CODE HERE------------>


In [ ]:
np.seed(23)

# Generate a new array of random numbers, this time of shape (3, 2) and print it.
# What happens when you re-run the code now?
# TIP: you might want to save the result to compare the previous and the new one

#<------------INSERT CODE HERE------------>


# Think: what does np.seed() do? (Use Google if you don't know!)

#### Combine arrays

In [ ]:
arr1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8], [5, 6, 7 , 8]])

# Print the shapes of arr1 and arr2 and cat after each of the types of concatenations.
# Concatenating arrays is a very common operation. Make sure you understand it!
# TIP: it might help you to print the actual cat array after each type of concatenation too

#<------------INSERT CODE HERE------------>


# concatenate along the row
cat = np.concatenate((arr1, arr2), axis=0)
#<------------INSERT CODE HERE------------>


# concatenate along the column
cat = np.concatenate((arr1, arr2), axis=1)    
#<------------INSERT CODE HERE------------>


# stack arrays vertically
cat = np.vstack((arr1, arr2))
#<------------INSERT CODE HERE------------>

# stack arrays horizontally
cat = np.hstack((arr1, arr2))
#<------------INSERT CODE HERE------------>


#### Operations with arrays

In [ ]:
#Let's create a couple of vectors using numpy
v1 = np.array([20, 30, 40, 50])
v2 = np.arange(4)

#And a couple of matrices
mat1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
mat2 = mat1.T # this is the transpose of mat1

In [ ]:
# Add a number to an array of 1-D (i.e., a vector)
print(5 + v1)
# Compare the line above to your function vector_plus_num(vector, number) from Part 1.

# Does your function work with matrices?

# How do you add a number to a np.array object? Try adding 2367 to mat1

#<------------INSERT CODE HERE------------>



In [ ]:
# Let's try to add and subtract vectors now:
print("Adding two vectors", v1 + v2)
print("Subtracting two vectors", v1 - v2)

# What happens if you try to add two vectors of different length?


# Square root of each elemnt of v2:
print(np.sqrt(v2))

# Calculate the logarithm of each element of v1
# TIP: check if you can do this using some numpy function!

#<------------INSERT CODE HERE------------>



### Multiplication of vectors

There are a number of functions in numpy that you can use to multiply vectors and matrices.

Scalar product of two vectors: np.dot(vector1, vector2)

Vector product of two vectors: np.cross(x, y)

In [ ]:
# Calculate the scalar product of v1 and v2 using your function from part 1 and the numpy function.
#<------------INSERT CODE HERE------------>


# Check if the result is the same using your function from Part 1

#<------------INSERT CODE HERE------------>


v3 = np.random.randn(4000)
v4 = np.random.randn(4000)
# Calculate the scalar product of v3 and v4 using your function from part 1 and the numpy function.
# Compare the time it takes to execute each of them.
# HINT: https://stackoverflow.com/questions/7370801/measure-time-elapsed-in-python

#<------------INSERT CODE HERE------------>



In [ ]:
# Calculate the vector product of v1 and v2 using the numpy function.

#<------------INSERT CODE HERE------------>

### Matrix multiplication

This can be done on numpy using: np.matmul(a, b)

In [ ]:
# Check the result of multiplying mat1 and mat2 using the numpy function and the one you created in part 1.
# Check the execution time for each of them. Which one is faster? 

#<------------INSERT CODE HERE------------>

# Is it the same result?

#<------------INSERT CODE HERE------------>

**Plotting a function**

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.figure()
plt.plot(t, sin)
plt.xlabel("Time")
plt.ylabel("sin(1/4*pi*t)")
plt.title("Sinusoidal function")
plt.show()

In [ ]:
print(np.max(sin))
print(np.min(sin))

## Elementwise minimum and maximum
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

In [ ]:
# Statistical summaries 

print(np.mean(randn))
print(np.median(randn))
print(np.std(randn))



Create a 5 (channels) x 100 (samples) matrix of random integers between 0 and 543 and retrieve the following information:
    - the max, min, mean of all samples.
    - the mean and variance of each channel


In [ ]:
#<------------INSERT CODE HERE------------>

Use the function hist() from matplotlib to show the histogram of values of the third channel.

In [ ]:
#<------------INSERT CODE HERE------------>